---
branches:
  - name: master
    prerelease: beta
  - name: production
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "./prepare_release.sh ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets:
      - VERSION
      - CHANGELOG.md
  - - "@semantic-release/github"
    - assets:
      - path: dist/**
